import ShoppingCart from "@/components/global/shopping-cart";
import SmoothFollower from "@/components/ui/cursor-follow";
import { ShoppingCartProvider } from "@/context/shopping-cart-context";
import { WishlistDrawerProvider } from "@/context/wishlist-drawer-context";
import WishlistDrawer from "@/components/global/wishlist-drawer";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-rose-50/70 antialiased`}
        suppressHydrationWarning
      >
        <WishlistDrawerProvider>
          <ShoppingCartProvider>
            <ShoppingCart />
            <SmoothFollower />
            <main>{children}</main>
            <WishlistDrawer />
          </ShoppingCartProvider>
        </WishlistDrawerProvider>
      </body>
    </html>
  );
}
